In [1]:
from IPython.display import display, Math, Latex
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageFilter
import os, os.path
import glob
from copy import deepcopy, copy
from math import trunc, log

In [ ]:
ima = []
for filename in glob.glob('imagesHW2/*.jpg'): #assuming gif
    im=Image.open(filename)
    im = im.convert('L')
    ima.append(im)

In [ ]:
from scipy.linalg import hadamard
M=1; n=2**M
H=hadamard(n)
print(H)

In [ ]:
M=2; n=2**M
H=hadamard(n)
print(H)

In [ ]:
def walsh(x):
    
    #x = np.array(x)
    if(len(x.shape)<2): # make sure n is 1D
        if(len(x)>3): # make sure M = 2
            n = len(x)
            m = trunc(log(n,2))
            x = x[0:2**M]
            H2 = np.array([[1,1],[1,-1]])
            for i in range(M-1):
                if i==0:
                    H = np.kron(H2,H2)
                else:
                    H = np.kron(H,H2)
                    
            return (np.dot(H,x)/2.**M,x, M)
        else:
            print("array too short")
    else:
        print("1d array expected")
    

In [ ]:
test = np.asarray(ima[0])

In [ ]:
test.shape

In [ ]:
flat = test.flatten()

In [ ]:
flat


In [ ]:
a = walsh(flat)

In [ ]:
a

In [ ]:
b = np.reshape(a, test.shape)

In [60]:
A = np.zeros((4,4), dtype=int)

In [61]:
A


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [63]:
B = np.zeros((2,2), dtype=int)
B

array([[0, 0],
       [0, 0]])

In [64]:
B[0][0]=1
B[0][1]=1
B[1][0]=1
B[1][1]=-1

In [65]:
B

array([[ 1,  1],
       [ 1, -1]])

In [66]:
r,c = 0,0
A[r:r+B.shape[0], c:c+B.shape[1]] += B

In [68]:
r,c = 0,2
A[r:r+B.shape[0], c:c+B.shape[1]] += B

In [70]:
r,c = 2,0
A[r:r+B.shape[0], c:c+B.shape[1]] += B

In [71]:
r,c = 2,2
A[r:r+B.shape[0], c:c+B.shape[1]] += -B

In [86]:
A.shape

(4, 4)

In [87]:
B.shape

(2, 2)

In [107]:
test = np.zeros((1,1), dtype=int)

In [108]:
print(test)

[[0]]


In [92]:
test.shape[0]*2 

2

In [81]:
test[0]=1
test

array([[1]])

In [85]:
test = int(log(8,2))
test

3

In [94]:
r1,c1 = test.shape[0], test.shape[0]

In [95]:
r1

1

In [96]:
c1

1

In [115]:
def hada(N):
    H = np.zeros((1,1), dtype=int)
    H[0] = 1
    log_N = int(log(N,2))
    shape = H.shape[0]
    while log_N>0:
        A = np.zeros((H.shape[0]*2,H.shape[0]*2),dtype=int)
        r1,c1 = 0,0
        r2,c2 = 0, H.shape[0]
        r3,c3 = H.shape[0],0
        r4,c4 = H.shape[0], H.shape[0]
        A[r1:r1+H.shape[0], c1:c1+H.shape[1]] = H
        A[r2:r2+H.shape[0], c2:c2+H.shape[1]] = H   
        A[r3:r3+H.shape[0], c3:c3+H.shape[1]] = H
        A[r4:r4+H.shape[0], c4:c4+H.shape[1]] = -H
        H = A
        log_N -= 1
    return H
    
    

In [109]:
hada(2)

array([[1]])

In [116]:
H = hada(8)

[[ 1  1]
 [ 1 -1]]
[[ 1  1  1  1]
 [ 1 -1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]]
[[ 1  1  1  1  1  1  1  1]
 [ 1 -1  1 -1  1 -1  1 -1]
 [ 1  1 -1 -1  1  1 -1 -1]
 [ 1 -1 -1  1  1 -1 -1  1]
 [ 1  1  1  1 -1 -1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1]
 [ 1 -1 -1  1 -1  1  1 -1]]


In [117]:
H

array([[ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 1, -1,  1, -1,  1, -1,  1, -1],
       [ 1,  1, -1, -1,  1,  1, -1, -1],
       [ 1, -1, -1,  1,  1, -1, -1,  1],
       [ 1,  1,  1,  1, -1, -1, -1, -1],
       [ 1, -1,  1, -1, -1,  1, -1,  1],
       [ 1,  1, -1, -1, -1, -1,  1,  1],
       [ 1, -1, -1,  1, -1,  1,  1, -1]])

In [123]:
x = np.zeros((4,4), dtype=int)
haar_2d(4,4,x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])